### ISSUE TITLE
Failes to parse modules that use but don't explicitly enable MultiParamsTypeClasses

### ISSUE THREAD

**Issue by janpath** [jaspervdj/stylish-haskell#152] opened 2017-02-06 10:26 UTC
### Steps to reproduce:
1. Create file with following contents:

       -- File: test.hs
       module Test where
       import Control.Monad.State.Class

       test :: MonadState s m => m ()
       test = undefined

2. Verify that this compiles with GHC.
3. Run `stylish-haskell test.hs`.

### Expected
Since GHC accepts the file `stylish-haskell` should too.

### Actual result
`stylish-haskell` fails to parse the file with the following message.

    Language.Haskell.Stylish.Parse.parseModule: could not parse ../test.hs:
     ParseFailed (SrcLoc "<unknown>.hs" 6 27) 
     "MultiParamTypeClasses language extension is not enabled. Please add
     {-# LANGUAGE MultiParamTypeClasses #-} pragma at the top of your module."

### Version:
    
    $ stack exec -- stylish-haskell --version
    stylish-haskell 0.7.1.0
    $ git rev-parse HEAD
    6df99cb50b5292c578d7c96f5753749b9d938b72

**Comment by lehins** [comment] 2017-03-04 16:01
This seems to be a duplicate of #103

**Comment by neongreen** [comment] 2017-04-16 01:00
Yes, a duplicate.

**Closed by neongreen** 2017-04-16 01:00 UTC
