### ISSUE TITLE
{-@ HTF_TESTS @-} comments are removed

### ISSUE THREAD

**Issue by agrafix** [jaspervdj/stylish-haskell#151] opened 2017-01-27 11:00 UTC
Same issue with other comments like the ones required and used by [HTF](https://hackage.haskell.org/package/HTF):

``` haskell
{-# OPTIONS_GHC -F -pgmF htfpp #-}
module Main where

import Test.Framework
import Test.Framework.BlackBoxTest
import {-@ HTF_TESTS @-} MyPkg.A
import {-@ HTF_TESTS @-} MyPkg.B

main = htfMain htf_importedTests
```

turns into:

``` haskell
{-# OPTIONS_GHC -F -pgmF htfpp #-}
module Main where

import Test.Framework
import Test.Framework.BlackBoxTest
import MyPkg.A
import MyPkg.B

main = htfMain htf_importedTests
```

(See #70 )

**Comment by neongreen** [comment] 2017-04-15 20:40
These are ordinary comments, not pragmas (the issue persists if you remove `@`, for instance), so I think it's a duplicate of https://github.com/jaspervdj/stylish-haskell/issues/39.

**Closed by neongreen** 2017-04-15 20:40 UTC
Labels: lossy
