### ISSUE TITLE
Unable to parse `BlockArguments` syntax

### ISSUE THREAD

**Issue by fosskers** [jaspervdj/stylish-haskell#229] opened 2019-01-02 17:56 UTC
GHC 8.6 introduced the new `BlockArguments` pragma, which allows us to pass `do` blocks, lambda, etc. as function arguments:
```haskell
unless someCondition do
  fireTheMissles
  bakeCookies
  callMom
```
whereas previously we'd expect a `$` between `someCondition` and `do`.

It seems that `stylish-haskell` is unable to parse this syntax. At least, my integrated in-buffer auto-restyling seems to not activate anymore when I use this syntax. I tried using a `stylish-haskell` built with `lts-13`, hoping that would grab a fresh `ghc-src-exts`, but that didn't work either.

Thoughts? Thank you for a great tool!

**Comment by fosskers** [comment] 2019-01-04 14:45
Oh, perhaps this is an issue with `haskell-src-exts`.

**Comment by fosskers** [comment] 2019-01-04 15:12
Almost certainly yes:
```haskell
colin@yumi ~/c/h/k/l/D/Kanji> stylish-haskell Web.hs 
Language.Haskell.Stylish.Parse.parseModule: could not parse Web.hs: ParseFailed (SrcLoc "<unknown>.hs" 40 19) "Parse error: do"
```

**Comment by simonchatts** [comment] 2019-02-12 21:36
Same goes for `DerivingVia`:
```
$ stylish-haskell Types.hs 
Language.Haskell.Stylish.Parse.parseModule: could not parse Types.hs: ParseFailed (SrcLoc "<unknown>.hs" 90 9) "Parse error: via"
```
Also more thanks for a great tool!

**Comment by ttuegel** [comment] 2019-02-18 16:13
And also `QuantifiedConstraints`, as it happens.

**Comment by jaspervdj** [comment] 2019-03-10 17:06
Yes, these parsing issues are caused by `haskell-src-exts`, which sometimes needs some time to catch up with GHC.

**Comment by ChShersh** [comment] 2019-03-29 08:31
@jaspervdj `haskell-src-exts-1.21.0` was released with the support for `DerivingVia`. Would it be possible to upload new release of `stylish-haskell` to Hackage to support for the new version of `haskell-src-exts` library?

**Comment by vrom911** [comment] 2019-04-29 08:10
@jaspervdj any updates on this? Is it blocked by anything?

**Comment by fosskers** [comment] 2019-04-29 14:49
Shouldn't be, here's a PR: https://github.com/jaspervdj/stylish-haskell/pull/234

**Comment by carlosdagos** [comment] 2019-06-20 01:16
Pretty sure this one can be closed @jaspervdj 😄 Thanks!

**Comment by jaspervdj** [comment] 2019-06-20 07:57
Sorry for the delay!

**Closed by jaspervdj** 2019-06-20 07:57 UTC

**Comment by fizruk** [comment] 2019-07-02 00:13
Hmm, I am still getting a parse error with this version:

```sh
$ stylish-haskell --version
stylish-haskell 0.9.2.2
```
```
$ stylish-haskell -i test.hs
Language.Haskell.Stylish.Parse.parseModule: could not parse test.hs: ParseFailed (SrcLoc "<unknown>.hs" 17 24) "Parse error: do"
```

```haskell
-- test.hs
module Main where

someCondition :: Bool
someCondition = False

fireTheMissles :: IO ()
fireTheMissles = putStrLn "Missles fired!"

bakeCookies :: IO ()
bakeCookies = putStrLn "Here are your cookies!"

callMom :: IO ()
callMom = putStrLn "Hey there!"

main :: IO ()
main = do
  unless someCondition do
    fireTheMissles
    bakeCookies
    callMom
```

**Comment by fosskers** [comment] 2019-07-02 14:38
@fizruk are you positive you compiled `stylish-haskell` with the most recent version of `haskell-src-exts`?

**Comment by fizruk** [comment] 2019-07-03 07:39
@fosskers

First I tried this

```
stack install stylish-haskell-0.9.2.2
```

but then I also tried this

```
stack install stylish-haskell-0.9.2.2 haskell-src-exts-1.21.0
```

The result is the same, global resolver is `lts-13.4`.

What is the correct way to install `stylish-haskell` with the most recent version of `haskell-src-exts`?

**Comment by ShrykeWindgrace** [comment] 2019-07-03 08:47
Just for info, with `lts-13.27` (`stylish-haskell-0.9.2.2` and `haskell-src-exts-1.20.3`) and with `nightly-2019-07-02` (`stylish-haskell-0.9.2.2` and `haskell-src-exts-1.21.0`) the problem is still there.

**Comment by RatanRSur** [comment] 2019-09-15 13:48
I'm also still seeing it, here's a file that repros it:

```
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE PartialTypeSignatures #-}
module Bandwidth where

import           Base16Colors (red)
import           Control.Exception  (try)
import           Data.Strings       (strStartsWith)
import           GHC.IO.Handle      (hGetContents)
import           System.Environment (getEnv)
import           System.Process     (StdStream (CreatePipe), createProcess,
                                     proc, std_out)
import           Text.Show.Unicode (uprint)

isDefault :: String -> Bool
isDefault str = strStartsWith str "default"

constructOutputLines :: Bool -> String -> [String]
constructOutputLines interfaceStatus interfaceName =
    if not interfaceStatus
    then let downMessage = interfaceName ++ " ▼"
         in [downMessage, downMessage, red]
    else replicate 2 "Success"

getInterfaceName :: IO(String)
getInterfaceName = do
    (_, Just stdoutHandle, _, _) <- createProcess (proc "ip" ["route"]) { std_out = CreatePipe }
    ipRouteOutput <- hGetContents stdoutHandle
    let defaultInterfaceName = (words $ head $ filter isDefault $ lines ipRouteOutput) !! 4
    providedInterfaceNameResult <- try $ getEnv "BLOCK_INSTANCE" :: _ (_ IOError _)
    return case providedInterfaceNameResult of
        Left _         -> defaultInterfaceName
        Right provided -> provided

isInterfaceUp :: String -> IO(Bool)
isInterfaceUp interfaceName =
    fmap isUp
       $ (try $ readFile $ "/sys/class/net/" ++ interfaceName ++ "/operstate" :: _ (_ IOError _))
     where isUp operStateResult = case operStateResult of
            Left _         -> False
            Right contents -> contents == "up\n"

main :: IO ()
main = do
    interfaceName <- getInterfaceName
    interfaceUp <- isInterfaceUp interfaceName
    mapM_ uprint $ constructOutputLines interfaceUp interfaceName
```

**Comment by matthewess** [comment] 2020-03-12 03:13
Still getting this one at least up to version `0.10.0.0`, should this issue be reopened?

**Comment by friedbrice** [comment] 2020-03-13 05:00
Same, compiled `stylish-haskell 0.10.0.0` with `stack resolver lts-15.3`. Chokes on `BlockArguments`.

```
Language.Haskell.Stylish.Parse.parseModule: could not parse server/lib/Lumi/Powerpuff/Lib/Mailer.hs: ParseFailed (SrcLoc "<unknown>.hs" 242 60) "Parse error: Last statement in a do-block must be an expression"
make: *** [Makefile:88: imports] Error 123
```

Here's the offending code:

```
  for_ (dedupeEmails $ recipients <> subscribers) \email -> do
    ...
```

**Comment by simonchatts** [comment] 2020-03-13 08:58
Silly question, but do you have `BlockArguments` enabled in `.stylish-haskell`'s `language_extensions`? This is installed via nix rather than stack, but:
```
% stylish-haskell --version
stylish-haskell 0.10.0.0
% stylish-haskell src/Test.hs

foo dedupeEmails recipients subscribers =
  for_ (dedupeEmails $ recipients <> subscribers) \email -> do
    undefined
```
ie works on my machine™. Here `BlockArguments` is enabled in `.stylish-haskell` and the cabal file.

**Comment by friedbrice** [comment] 2020-03-13 17:41
@simonchatts I have the pragma at the top of my file. Sorry I didn't make that clear :-)

**Comment by parsonsmatt** [comment] 2020-03-13 17:44
`stylish-haskell` will work with this provided that you build it with `haskell-src-exts-1.23.0`. You can do this in a few ways:

1. Edit your global project (`~/.stack/global-project/stack.yaml`) to set `haskell-src-exts-1.23.0` as an `extra-dep`, and then do `stack install stylish-haskell`
2. Edit whatever project `stack.yaml` you have handy and set `haskell-src-exts-1.23.0` as an `extra-dep`, and then do `stack install stylish-haskell` from that project.
3. Run `stack exec --no-ghc-package-path -- cabal new-install stylish-haskell` which will automatically pull dependencies and use the GHC provided by `stack` (may require you to call `stack install cabal-install`)
