### ISSUE TITLE
instance with 2 constraints not parsed

### ISSUE THREAD

**Issue by eallik** [jaspervdj/stylish-haskell#88] opened 2015-05-13 12:17 UTC
```
instance (Foo k, Foo v) => Foo (Map k v) where
  foo m = undefined
```

yields

> Error: stylish-haskell ended with errors, leaving buffer alone

whereas `instance Foo k => Foo (Map k v) where ...` works fine.

**Comment by bergmark** [comment] 2015-05-13 12:19
I can't reproduce this problem.

**Comment by eallik** [comment] 2015-05-13 12:56
```
~/code/haskell$ cat stylish.hs 
instance Foo k => Foo (Map k v) where
  foo m = undefined
~/code/haskell$ stylish-haskell stylish.hs 
{-# LANGUAGE UnicodeSyntax #-}
instance Foo k ⇒ Foo (Map k v) where
  foo m = undefined
~/code/haskell$ cat stylish.hs 
instance (Foo k, Foo v) => Foo (Map k v) where
  foo m = undefined
~/code/haskell$ stylish-haskell stylish.hs 
stylish-haskell: Language.Haskell.Stylish.Editor.applyChanges: refusing to make overlapping changes
```

**Comment by eallik** [comment] 2015-05-13 12:58
I'm on version `0.5.11.2`.

**Comment by eallik** [comment] 2015-12-21 12:09
ping

**Comment by jaspervdj** [comment] 2016-01-31 16:24
Can you try using the latest version of `stylish-haskell`? I am getting:

```
jasper@colony6 ~/Desktop> cat test.hs
instance (Foo k, Foo v) => Foo (Map k v) where
  foo m = undefined
jasper@colony6 ~/Desktop> stylish-haskell test.hs
instance (Foo k, Foo v) => Foo (Map k v) where
  foo m = undefined
jasper@colony6 ~/Desktop>
```

**Comment by neongreen** [comment] 2017-04-15 20:21
Works for me as well, closing. Please reopen this issue if you can reproduce it with latest stylish-haskell.

**Closed by neongreen** 2017-04-15 20:21 UTC
