### ISSUE TITLE
comments on imports disappear

### ISSUE THREAD

**Issue by willtim** [jaspervdj/stylish-haskell#131] opened 2016-09-14 09:24 UTC
stylish is great, but I feel this is not a small issue, as it means stylish is essentially a lossy transform.
e.g.
import Foo.Bar.Baz -- this comment won't survive!

**Comment by osa1** [comment] 2016-10-12 17:26
:+1: came here to report this, I can't document my imports anymore!

**Comment by siddharthist** [comment] 2017-01-20 05:10
Duplicate of #39

**Comment by neongreen** [comment] 2017-04-15 19:38
Closing in favor of #39.

**Closed by neongreen** 2017-04-15 19:38 UTC
